trigger:
  - main  # Runs when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Uses an Ubuntu machine to run the script

steps:
  - script: echo "Hello, World from Azure DevOps!"
    displayName: 'Print Hello World'
