trigger:
  - main  # Runs the pipeline when changes are pushed to the main branch

pool:
  name: 'MyProject'  # Uses an Ubuntu machine to run the pipeline


steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'  # ✅ Fix: Add this option

  - checkout: self

  - script: |
      javac HelloWorld.java
      java HelloWorld
    workingDirectory: '$(https://github.com/swatisinha-08/Hello_World)'
    displayName: 'Compile and Run Java Program'