trigger:
  - main  # Runs the pipeline when changes are pushed to the main branch

pool:
  name: 'MyProject'  # Uses an Ubuntu machine to run the pipeline

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'  # Change based on the Java version needed
      jdkArchitecture: 'x64'

  - checkout: self  # Clones your GitHub repo into $(Build.SourcesDirectory)

  - script: |
      javac HelloWorld.java  # Compile Java file
      java HelloWorld        # Run Java program
    workingDirectory: '$(https://github.com/swatisinha-08/Hello_World)'  # Your repo root directory
    displayName: 'Compile and Run Java Program'