trigger:
  - main  # Runs the pipeline when changes are pushed to the main branch

pool:
  name: 'MyProject'  # Uses an Ubuntu machine to run the pipeline

steps:
  - script: |
      echo "Compiling Java Program..."
      javac HelloWorld.java
      echo "Running Java Program..."
      java HelloWorld
    displayName: 'Compile and Run Java Program'
