trigger:
  - main  # Runs the pipeline when changes are pushed to the main branch

pool:
  name: 'MyProject'  # Change this to your actual agent pool name

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Build .NET Project'
    inputs:
      command: 'build'
  
  - script: echo "Hello, World from Azure DevOps!"
    displayName: 'Print Hello World'
